In [56]:
import numpy as np         
import pandas as pd

In [57]:
df = pd.read_csv('C:\Github\Credit_risk_analysis_with_ExplainableAI\data\processed\cleaned_loan_data.csv')

In [58]:
df.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,22.0,59000.0,17.0,29800.0,16.02,1,0.59,1,3,0,0,1,0,0,0,0,1,0
1,21.0,9600.0,5.0,1000.0,11.14,0,0.10,0,2,0,1,0,0,1,0,0,0,0
2,25.0,9600.0,1.0,5500.0,12.87,1,0.57,0,3,0,0,0,0,0,0,1,0,0
3,23.0,65500.0,4.0,29800.0,15.23,1,0.53,0,2,0,0,1,0,0,0,1,0,0
4,24.0,54400.0,8.0,29800.0,14.27,1,0.55,1,4,0,0,1,0,0,0,1,0,0

In [59]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
count,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000
mean,27.671459,64354.202770,4.728653,9560.835698,11.014662,0.218688,0.170250,0.176765,5.811297,0.003270,0.079066,0.505244,0.160075,0.197773,0.110871,0.186389,0.169608,0.175284
std,5.921032,37800.895594,3.851410,6203.174732,3.083050,0.413363,0.106812,0.381475,4.059030,0.057091,0.269846,0.499980,0.366682,0.398326,0.313977,0.389427,0.375293,0.380216
min,20.000000,4000.000000,0.000000,500.000000,5.420000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,38542.000000,2.000000,5000.000000,8.490000,0.000000,0.090000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,26.000000,55000.000000,4.000000,8000.000000,10.990000,0.000000,0.150000,0.000000,4.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,30.000000,79218.000000,7.000000,12250.000000,13.110000,0.000000,0.230000,0.000000,8.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,50.000000,225000.000000,17.000000,29800.000000,23.220000,1.000000,0.830000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

X = df.drop('loan_status', axis=1)
y = df['loan_status']

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(22691, 17) (9725, 17) (22691,) (9725,)

In [62]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [63]:
dt_model = DecisionTreeClassifier(class_weight='balanced', random_state=42)
dt_model.fit(X_train, y_train)
y_pred = dt_model.predict(X_test)
print('Accuracy Score:', accuracy_score(y_test, y_pred))
print('Confusion Matrix:', confusion_matrix(y_test, y_pred))
print('Classification Report:', classification_report(y_test, y_pred))

Accuracy Score: 0.8795886889460154
Confusion Matrix: [[6983  586]
 [ 585 1571]]
Classification Report:               precision    recall  f1-score   support

           0       0.92      0.92      0.92      7569
           1       0.73      0.73      0.73      2156

    accuracy                           0.88      9725
   macro avg       0.83      0.83      0.83      9725
weighted avg       0.88      0.88      0.88      9725

In [64]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)
print('Accuracy Score:', accuracy_score(y_test, y_pred))
print('Confusion Matrix:', confusion_matrix(y_test, y_pred))
print('Classification Report:', classification_report(y_test, y_pred))

Accuracy Score: 0.9175321336760925
Confusion Matrix: [[7460  109]
 [ 693 1463]]
Classification Report:               precision    recall  f1-score   support

           0       0.92      0.99      0.95      7569
           1       0.93      0.68      0.78      2156

    accuracy                           0.92      9725
   macro avg       0.92      0.83      0.87      9725
weighted avg       0.92      0.92      0.91      9725

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
              'n_estimators': [50, 100, 200],
              'max_depth': [10, 20, 30, 40, 50 , None],
              'min_samples_split': [2, 5, 10],
              'min_samples_leaf': [1, 2, 4],
              'max_features': ['sqrt', 'log2']
              }

rf_model = RandomForestClassifier(random_state=42 , n_jobs=1)

grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)
print(grid_search.best_score_)
print(grid_search.best_estimator_)
y_pred = grid_search.best_estimator_.predict(X_test)
print('Accuracy Score:', accuracy_score(y_test, y_pred))
print('Confusion Matrix:', confusion_matrix(y_test, y_pred))
print('Classification Report:', classification_report(y_test, y_pred))

Fitting 5 folds for each of 324 candidates, totalling 1620 fits

In [55]:
import pickle

# Save the best model from grid search (the tuned RandomForest model)
with open('random_forest_model.pkl', 'wb') as model_file:
    pickle.dump(grid_search.best_estimator_, model_file)